name: Run echo

on: 
    workflow_call: 

        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Checkout repository of reusable action
          uses: actions/checkout@v4
          with:
            repository: sparkmuse/sharedworkflows
            ref: d6a8a7e0542e813d43326bfaa6b2b08613d07441
            path: ./sharedactions

        - run: ls ./sharedactions/.github/actions -a

        - name: Use it
          uses: ./sharedactions/.github/actions/echo-hello-world
