name: Run echo

on: 
    workflow_call: 

        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Checkout repository of reusable action
          uses: actions/checkout@v4
          with:
            repository: sparkmuse/sharedworkflows
            path: sharedactions
        
        - name: Use it
          uses: sharedactions/.github/actions/echo-hello-world@v2
